apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-deployment
  template:
    metadata:
      labels:
        app: flask-deployment
    spec:
      containers:
      - name: flask-app
        image: nikhilramagiri/my-flask-app:0.0.1
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-deployment
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30007